[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.81.0"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

[[redirects]]
from = "/docs/v3.4.0/branch-management"
to = "/docs/v3.4.0/branch_management"
status = 301
force = false

[[redirects]]
from = "/docs/v3.4.0/reporting-bugs"
to = "/docs/v3.4.0/reporting_bugs"
status = 301
force = false

